---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab
  namespace: kube-system
  labels:
    app: ab
spec:
  replicas: 1
  template:
    metadata:
      name: ab
      labels:
        app: ab
    spec:
      containers:
        - name: ab
          image: registry.cn-hangzhou.aliyuncs.com/caojiaoyue/ab:test10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      serviceAccountName: ab
      restartPolicy: Always
  selector:
    matchLabels:
      app: ab
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ab
  name: ab-svc
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ab
  sessionAffinity: None
  type: NodePort
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.morven.me
    clientConfig:
      service:
        namespace: "example-namespace"
        name: "example-service"
        path: /my-path
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1","v1beta1"]
        resources: ["deployments", "replicasets"]
        scope: "Namespaced"
