---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab
  namespace: kube-system
  labels:
    app: ab
spec:
  replicas: 1
  template:
    metadata:
      name: ab
      labels:
        app: ab
    spec:
      containers:
        - name: ab
          image: registry.cn-hangzhou.aliyuncs.com/caojiaoyue/ab:test10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      serviceAccountName: ab
      restartPolicy: Always
  selector:
    matchLabels:
      app: ab
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ab
  name: ab-svc
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ab
  sessionAffinity: None
  type: NodePort
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.morven.me
    clientConfig:
      service:
        namespace: "kube-system"
        name: "ab-svc"
        path: /ab/webhook
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EY3pNREV4TWpFek9Wb1hEVEk1TURjeU56RXhNakV6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEd3CnJJYTlpYlh4N1ZEczNVMkpkQnNxQ0JFbUNrWHBYeWZjSkh2czJScjBPaHRmbk5aY1EyK1JOaHFSQkR4Uk5zb20KYUVZaWlPaG9OeDBBUXlBYVNTZzZyZlVkaDh0cmErL3dpaTR0UzdBWGJQV3czc0FEcWFUZWMxYk1TZnNEdHpmRwpkTHZXOSt2em9hdGJ3UTNwOThyY2NMN0JZSHEzK2V2eDRmR3VGMFZWR3Mzc0h4bk1CZEVNZi81WmRCRXVlMHErCk5FMmkyWUphOWoyZm5pOEVzZ0EyUlhZdXJNWHBzZWt0Y0ROUDQvQURLZWdCTDJoaXhndUpGUmQ1ZHpDZ2p0eG8KNlhSaWVyekJUaW1qSGxtTnNpV3hFYTF1SFZpai96clJOaVpjQ2swTytSQ3ZCNmlUckp6UmZLVmdkbFBDbkl0RgpMNk9nRGlWOWNOZHFjcXFCcDFrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKVEU5b3oraGxOdzlXY1BlNFRsQ3hDQUhQMFIKRnpCT3A3Q2dzMFpWSS9RQzlLeU9tc1Y2Q2FwamlPMVpGa2JqQjFsa3Z5a05jR1JwOGtyR0dKWWQ5RExOckVSMgpFMzZiS0d2WDh0b1k5REZXWUQvbHlUNmF5Z0tGT0lCSE80eUdEWUthZU5odzZxcXZhbDZMM0hDbmc2YW00Y00rCmhwekFjSXFERHZTZldNT3dzZTVCeFUzUXRyYVNhTU1QMDlHWWFVNklMUXM1K09XWllMT014WlQzZTk1Q3F1OXgKenB3TS9UQjMwVHk1YTE1K2hvTmV1Y2ZsTHhURzlkNWZsL1Q0bldKTkFmQklDMndtdDRMMWs1bm1MSTdLbGJGcAppVk01cy9LTkNmRXhEdm1TNFJHNm1WS0ZXSzdSZ00wZTA5cmdnbUFEWlRzSHNLWDNDV0cySWVvSDZ3ST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1","v1beta1"]
        resources: ["deployments",]
        scope: "Namespaced"
